name: Back-end tests

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

defaults:
  run:
    working-directory: ./backend

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: KGn]FCx0w~TI
      JWT_EXPIRATION_TIME: 600000
      secure: false
      HCAPTCHA_DEV_SECRET_KEY: '0x0000000000000000000000000000000000000000'
      HCAPTCHA_TEST_TOKEN: 10000000-aaaa-bbbb-cccc-000000000001
      NODE_ENV: development

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: seaqull
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Prepare for back-end tests
        run: |
          mv ormconfig.example.js ormconfig.js
          mv env.example env
          npm install
      - name: Setup and seed database
        run: npm run reset
      - name: Log all files in folder
        run: ls -a
      - name: Start back-end server
        run: npm start &
      - name: Wait for OK status
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:8000/api/health/ping'
          responseCode: 200
          timeout: 10000
          interval: 500
      - name: Run back-end tests
        run: npm test