name: Back-end tests

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

defaults:
  run:
    working-directory: ./backend

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_NAME: seaqull
      JWT_SECRET: KGn]FCx0w~TIdsfasdfAAd22
      JWT_EXPIRATION: 6000000
      SECURE: false
      NODE_ENV: development
      HCAPTCHA_DEV_SECRET_KEY: 0x0000000000000000000000000000000000000000
      HCAPTCHA_PROD_SECRET_KEY: 0x0000000000000000000000000000000000000001
      HCAPTCHA_TEST_TOKEN: 10000000-aaaa-bbbb-cccc-000000000001
      BACKEND_URL: http://localhost:8000/
      BACKEND_PORT: 8000
      SWAGGER_DOCS_ENDPOINT: docs
      BACKEND_TEST_URL: http://localhost:8000/api
      HCAPTCHA_SITE_VERIFY: https://hcaptcha.com/siteverify/


    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: seaqull
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 50
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Prepare for back-end tests
        run: |
          mv ormconfig.example.js ormconfig.js
          npm install
      - name: Setup and seed database
        run: npm run reset
      - name: Log all files in folder
        run: ls -a
      - name: Start back-end server
        run: npm start &
      - name: Wait for OK status
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:8000/api/health/ping'
          responseCode: 200
          timeout: 10000
          interval: 500
      - name: Run back-end tests
        run: npm test