name: Node.js CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

defaults:
  run:
    working-directory: ./backend

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: KGn]FCx0w~TI
      JWT_EXPIRATION_TIME: 600000
      RECAPTCHA_SECRET_KEY: 6LcuZr8cAAAAAFprJpiETSZ84zOK35JAb8EhGyKs
      secure: false
      PORT: 8000
      NODE_ENV: development
      CURRENT_APP_STATE: dev
      HCAPTCHA_DEV_SECRET_KEY: 0x0000000000000000000000000000000000000000

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: seaqull
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # TODO: Turned off these steps because we don't poll the back-end for a response yet. This means that the
      #       workflow never continues after 'npm start' because we don't detect whether it's started. Without
      #       starting the back-end we can't run the tests either. If we kept this running our github actions minutes
      #       would vanish. 
      #
      - name: Prepare for back-end tests
        run: |
          mv ormconfig.example.json ormconfig.json
          npm install
          npm run reset
      - name: Start back-end server
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:8000'
        working-directory: ./backend
      - name: Run back-end tests
        run: npm test